trigger:
  branches:
    include:
      - master  # Adjust as per your branch structure

pool:
  vmImage: 'windows-latest'


steps:
# Use Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Checkout source code
- checkout: self

# Install dependencies
- script: |
    python -m venv venv  # Create virtual environment
    venv\Scripts\activate  # Activate virtual environment (Windows)
    pip install --upgrade pip  # Upgrade pip
    pip install -r requirements.txt  # Install dependencies
  displayName: 'Install dependencies'

# Run pytest tests
- script: |
    venv\Scripts\python -c "import sys; print(sys.executable)"
    venv\Scripts\python -m pytest -n 10 --alluredir=allure-results --html=report.html
  displayName: 'Run pytest tests'

# Publish Allure test results
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'allure-results'  # Folder to store Allure test results
    ArtifactName: 'AllureReports'
    publishLocation: 'Container'

# Publish HTML report
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report.html'  # HTML report file
    ArtifactName: 'TestReports'
    publishLocation: 'Container'