name: Python Test Suite

on:
  push:
    branches:
      - main  # Replace with your default branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Add this line to allow manual triggering

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Set PowerShell Execution Policy
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Verify requirements.txt exists
        run: |
          if (Test-Path "requirements.txt") { Write-Host "requirements.txt found"; } else { Write-Host "requirements.txt not found"; exit 1; }
      - name: Install dependencies
        run: |
          echo "Checking if Activate.ps1 exists"
          dir "D:\a\PythonSeleniumRepo\PythonSeleniumRepo\venv\Scripts\Activate.ps1"
          python -m venv venv  # Create virtual environment
          & "D:\a\PythonSeleniumRepo\PythonSeleniumRepo\venv\Scripts\Activate.ps1"  # Activate virtual environment using full path
          echo "Virtual Environment Activated"
          & "D:\a\PythonSeleniumRepo\PythonSeleniumRepo\venv\Scripts\python" --version  # Full path to Python version check
          & "D:\a\PythonSeleniumRepo\PythonSeleniumRepo\venv\Scripts\python" -m pip --version  # Check pip version
          & "D:\a\PythonSeleniumRepo\PythonSeleniumRepo\venv\Scripts\python" -m pip install --upgrade pip -v  # Upgrade pip with verbose output
          & "D:\a\PythonSeleniumRepo\PythonSeleniumRepo\venv\Scripts\python" -m pip install -r requirements.txt -v  # Install dependencies
        shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
        env:
          pythonLocation: C:\hostedtoolcache\windows\Python\3.12.8\x64
          PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.12.8\x64/lib/pkgconfig
          Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.8\x64
          Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.8\x64
          Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.12.8\x64

      # Run pytest
      - name: Run pytest tests
        run: |
          .\venv\Scripts\python -c "import sys; print(sys.executable)"  # Check Python executable location
          .\venv\Scripts\python -m pip --version  # Check pip version
          .\venv\Scripts\python -m pytest -n 10 --browser_name=chrome --alluredir=allure-results --html=report.html

      # Upload Allure results as artifacts (optional)
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # Upload HTML test report (optional)
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: TestReports
          path: report.html
