name: Python Test Suite

on:
  push:
    branches:
      - main  # Replace with your default branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Add this line to allow manual triggering

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv  # Create virtual environment
          venv\Scripts\activate  # Activate virtual environment
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Run pytest
      - name: Run pytest tests
        run: |
          venv\Scripts\python -c "import sys; print(sys.executable)"
          venv\Scripts\python -m pytest -n 10 --browser_name=chrome --alluredir=allure-results --html=report.html

      # Upload Allure results as artifacts (optional)
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # Upload HTML test report (optional)
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: TestReports
          path: report.html
